/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author scarletspeedster
 */
public class RemoveAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoveAdmin
     */
    String username;
    Connection cn;
    PreparedStatement st;
    ResultSet rs;
    String sql;
    public void MyConnection()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/StudentManagement?autoReconnect=true&useSSL=true","scarlet","Lmno1996&&");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
            System.exit(0);
        }
    }
    public void Close()throws Exception
    {
        cn.close();
    }
    public RemoveAdmin() {
        MyConnection();
        initComponents();
        this.setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setClosable(true);
        setTitle("Remove Admin Rolls");
        setToolTipText("Remove Admin");
        setPreferredSize(new java.awt.Dimension(400, 250));

        jLabel1.setFont(new java.awt.Font("NanumMyeongjo", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Enter the Name:");

        jButton1.setText("Remove Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            username=tf1.getText();
            String []buttons={"No","Yes"};
            int n;
                sql="select * from Admin where Username=?";
                st=cn.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                st.setString(1,username);
                rs=st.executeQuery();
                rs.last();
                    if(rs.getRow()==0)
                    {
                        JOptionPane.showMessageDialog(this,"No Admin Found");
                        tf1.setText("");
                    }   
                        else
                        {
                            n=JOptionPane.showOptionDialog(this,
                            "Are You Sure You want to add this??","",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                             null,
                            buttons,buttons[0]);
                                if(n==1)
                                {
                                    sql="Delete from Admin where Username=?";
                                    st=cn.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                                    st.setString(1,username);
                                    st.executeUpdate();
                                    JOptionPane.showMessageDialog(this,"Admin Deleted SuccessFully");
                                    tf1.setText("");
                                    this.setVisible(false);
                                    Close();
                                }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(this,"Always take wise Decisions");
                                        tf1.setText("");
                                    }
                        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
